Created add/edit pollPage
vikash-kanauja/Poll-management_system pull request #5
Opened 2024-05-16 13:52 UTC by vikash-kanauja

2024-05-17 07:39 UTC, yuvrajKaexpertise commented on src/App.js
> +            <PrivateRoute Component={AddEditPollPage} redirectTo="/addedit" />
delete these route

2024-05-18 05:06 UTC, yuvrajKaexpertise requested changes

2024-05-18 05:06 UTC, yuvrajKaexpertise commented on src/pages/AddEditPollPage.js
> +import { useLocation, useNavigate, useParams } from "react-router-dom";
3rd party import should be from top @vikash-kanauja

2024-05-18 05:06 UTC, yuvrajKaexpertise commented on src/pages/AddEditPollPage.js
> +import { FaEdit } from "react-icons/fa";
these too @vikash-kanauja

2024-05-18 05:06 UTC, yuvrajKaexpertise commented on src/pages/AddEditPollPage.js
> +const AddEditPoll = () => {
function name should always start with smallcase @vikash-kanauja

2024-05-18 05:06 UTC, yuvrajKaexpertise commented on src/pages/AddEditPollPage.js
> +  const [showModal, setShowModal] = useState(false);
which modal @vikash-kanauja ?

2024-05-18 05:06 UTC, yuvrajKaexpertise commented on src/pages/AddEditPollPage.js
> +  const handleDeleteOption = () => {
what is handle handle handle every where? addPoll , deletePoll function name not enough? @vikash-kanauja

2024-05-18 05:06 UTC, yuvrajKaexpertise commented on src/pages/AddEditPollPage.js
> +      let result = {};
why do you need this result variable, if you are not using it @vikash-kanauja ?

2024-05-18 10:37 UTC, amrit56789 commented on src/pages/AddEditPollPage.js
> +  const [options, setOptions] = useState([]);
which options?

2024-05-18 10:38 UTC, amrit56789 commented on src/pages/AddEditPollPage.js
> +  const [showAddEditModal, setShowModal] = useState(false);
showAddEditModal and setShowModal ?????

2024-05-18 10:38 UTC, amrit56789 commented on src/pages/AddEditPollPage.js
> +  const [selectedIndex, setSelectedIndex] = useState(null);
which selectedIndex??

2024-05-18 10:39 UTC, amrit56789 commented on src/pages/AddEditPollPage.js
> +  const [editOption, setEditOption] = useState(null);
which editOptions

2024-05-18 10:40 UTC, amrit56789 commented on src/pages/AddEditPollPage.js
> +  const { loading } = useSelector((state) => state.pollList);
which loading?

2024-05-20 12:08 UTC, merged